name: Notes App CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres: &postgres_service
        image: postgres:15
        env:
          POSTGRES_DB: notes
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init-db
      - name: Build and Generate Jooq
        run: |
          ./gradlew clean
          ./gradlew jooqCodegen -PDB_URL=jdbc:postgresql://localhost:5432/notes -PDB_USER=user -PDB_PASSWORD=password 
          ./gradlew assemble

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      postgres: *postgres_service
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init-db
      - name: Run tests
        run: |
          ./gradlew clean
          ./gradlew jooqCodegen -PDB_URL=jdbc:postgresql://localhost:5432/notes -PDB_USER=user -PDB_PASSWORD=password 
          ./gradlew test